language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
     - platform-tools
     - tools

    # The SDK version used to compile your project
    - android-23
before_install:
  - chmod +x gradlew
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
